# Generated by Django 5.2.7 on 2026-01-11 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversaciones',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'chat_conversaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('activo', models.BooleanField()),
                ('correo_verificado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Denuncias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('referencia', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion_texto', models.TextField(blank=True, null=True)),
                ('origen', models.TextField()),
                ('estado', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'denuncias',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'departamentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TiposDenuncia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tipos_denuncia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChatMensajes',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(max_length=10)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.chatconversaciones')),
            ],
            options={
                'db_table': 'chat_mensajes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudadanos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.usuarios')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('foto_perfil_url', models.TextField(blank=True, null=True)),
                ('firma_url', models.TextField(blank=True, null=True)),
                ('firma_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ciudadanos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('tabla_afectada', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_id', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.usuarios')),
            ],
            options={
                'db_table': 'auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenunciaFirmas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('firma_url', models.TextField(blank=True, null=True)),
                ('firma_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('denuncia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias')),
            ],
            options={
                'db_table': 'denuncia_firmas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenunciaEvidencias',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo', models.TextField()),
                ('url_archivo', models.TextField()),
                ('nombre_archivo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias')),
            ],
            options={
                'db_table': 'denuncia_evidencias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chatconversaciones',
            name='denuncia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='asignado_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.departamentos'),
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('visible', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.usuarios')),
            ],
            options={
                'db_table': 'faq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_column='cedula', max_length=15, unique=True)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, db_column='cargo', max_length=100, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(db_column='created_at')),
                ('updated_at', models.DateTimeField(db_column='updated_at')),
                ('departamento', models.ForeignKey(blank=True, db_column='departamento_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.departamentos')),
                ('web_user', models.ForeignKey(blank=True, db_column='web_user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'funcionarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='denuncias',
            name='asignado_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.CreateModel(
            name='DenunciaRespuestas',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios')),
            ],
            options={
                'db_table': 'denuncia_respuestas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenunciaHistorial',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('estado_anterior', models.TextField(blank=True, null=True)),
                ('estado_nuevo', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias')),
                ('cambiado_por_funcionario', models.ForeignKey(blank=True, db_column='cambiado_por_funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios')),
            ],
            options={
                'db_table': 'denuncia_historial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DenunciaAsignaciones',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asignado_en', models.DateTimeField()),
                ('activo', models.BooleanField()),
                ('denuncia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios')),
            ],
            options={
                'db_table': 'denuncia_asignaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('leido', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.usuarios')),
            ],
            options={
                'db_table': 'notificaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetTokens',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_6', models.CharField(max_length=6)),
                ('expira_en', models.DateTimeField()),
                ('usado', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.usuarios')),
            ],
            options={
                'db_table': 'password_reset_tokens',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='denuncias',
            name='tipo_denuncia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.tiposdenuncia'),
        ),
        migrations.AddField(
            model_name='denuncias',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ciudadanos'),
        ),
        migrations.CreateModel(
            name='DenunciaBorradores',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('datos_json', models.JSONField()),
                ('listo_para_enviar', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('conversacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.chatconversaciones')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ciudadanos')),
            ],
            options={
                'db_table': 'denuncia_borradores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CiudadanoDocumentos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('url_frontal', models.TextField(blank=True, null=True)),
                ('url_trasera', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ciudadanos')),
            ],
            options={
                'db_table': 'ciudadano_documentos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chatconversaciones',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.ciudadanos'),
        ),
        migrations.CreateModel(
            name='FuncionarioRoles',
            fields=[
                ('pk', models.CompositePrimaryKey('funcionario_id', 'rol_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.roles')),
            ],
            options={
                'db_table': 'funcionario_roles',
                'managed': True,
                'unique_together': {('funcionario', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='TipoDenunciaDepartamento',
            fields=[
                ('tipo_denuncia', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='db.tiposdenuncia')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='db.departamentos')),
            ],
            options={
                'db_table': 'tipo_denuncia_departamento',
                'managed': True,
            },
        ),
    ]
