# Generated by Django 5.2.7 on 2026-01-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denunciaasignaciones',
            name='denuncia',
            field=models.ForeignKey(db_column='denuncia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciaasignaciones',
            name='funcionario',
            field=models.ForeignKey(db_column='funcionario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.AlterField(
            model_name='denunciahistorial',
            name='cambiado_por_funcionario',
            field=models.ForeignKey(blank=True, db_column='cambiado_por_funcionario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.AlterField(
            model_name='denunciahistorial',
            name='denuncia',
            field=models.ForeignKey(db_column='denuncia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciarespuestas',
            name='denuncia',
            field=models.ForeignKey(db_column='denuncia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciarespuestas',
            name='funcionario',
            field=models.ForeignKey(blank=True, db_column='funcionario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.AlterField(
            model_name='denuncias',
            name='asignado_departamento',
            field=models.ForeignKey(blank=True, db_column='asignado_departamento_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.departamentos'),
        ),
        migrations.AlterField(
            model_name='denuncias',
            name='asignado_funcionario',
            field=models.ForeignKey(blank=True, db_column='asignado_funcionario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.AlterField(
            model_name='funcionarioroles',
            name='funcionario',
            field=models.ForeignKey(db_column='funcionario_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
        migrations.AlterField(
            model_name='funcionarioroles',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.roles'),
        ),
    ]
