# Generated by Django 5.2.7 on 2026-01-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_denunciaasignaciones_denuncia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentos',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='chatconversaciones',
            name='denuncia',
            field=models.ForeignKey(blank=True, db_column='denuncia_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciaevidencias',
            name='denuncia',
            field=models.ForeignKey(db_column='denuncia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciafirmas',
            name='denuncia',
            field=models.OneToOneField(db_column='denuncia_id', on_delete=django.db.models.deletion.DO_NOTHING, to='db.denuncias'),
        ),
        migrations.AlterField(
            model_name='denunciahistorial',
            name='cambiado_por_funcionario',
            field=models.ForeignKey(blank=True, db_column='cambiado_por_funcionario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.funcionarios'),
        ),
    ]
